# Generated by Django 4.1.3 on 2022-11-30 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_activity"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="charged",
            field=models.BooleanField(default=False),
        ),
    ]
