# Generated by Django 4.1.3 on 2022-11-30 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_activity_charged"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="customer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="activities",
                to="accounts.customer",
            ),
        ),
    ]
