# Generated by Django 4.1.3 on 2022-12-09 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_activity_customer"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="dimension",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="customer",
            name="value",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=12),
        ),
    ]
