# Generated by Django 4.1.3 on 2022-12-15 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_customer_expiry_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="user",
        ),
        migrations.AddField(
            model_name="customer",
            name="company_name",
            field=models.CharField(default="EdgeIQ", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="customer",
            name="email",
            field=models.EmailField(default="jephter.danso@edgeiq.io", max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="customer",
            name="first_name",
            field=models.CharField(default="Jephter", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="customer",
            name="last_name",
            field=models.CharField(default="Danso", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="customer",
            name="phone_number",
            field=models.CharField(default="011111111111", max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="customer",
            name="title",
            field=models.CharField(default="Mr.", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="customer",
            name="customerID",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="customer",
            name="product_code",
            field=models.CharField(max_length=255),
        ),
    ]
