# Generated by Django 4.1.3 on 2022-12-16 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_remove_customer_user_customer_company_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="phone_number",
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AlterField(
            model_name="customer",
            name="title",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
